### ISSUE TITLE
Concurrency not supported

### ISSUE THREAD

**Issue by freahs** [ausrasul/mem_cache#1]
Mutating a map from multiple goroutines without synchronization is unsafe

**Comment by ausrasul** [comment]
aus@pop-os[master] ~/proj/web_mem_cache_2$ go test -bench=.
goos: linux
goarch: amd64
pkg: github.com/ausrasul/mem_cache
cpu: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
BenchmarkWrite-10                 678330              1755 ns/op
BenchmarkOverwrite-10            7072776               165.6 ns/op
BenchmarkRead-10                13578448                87.35 ns/op
BenchmarkReadMiss-10            15535848                76.80 ns/op

BenchmarkWriteGoMap-10           1000000              1684 ns/op
BenchmarkOverwriteGoMap-10      16609045                74.97 ns/op
BenchmarkReadGoMap-10           67565139                21.87 ns/op
BenchmarkReadMissGoMap-10       79819129                15.42 ns/op
PASS
ok      github.com/ausrasul/mem_cache   11.142s

**Comment by ausrasul** [comment]
I created another branch using channels as locks
https://github.com/ausrasul/mem_cache/tree/ch_lock

this is the benchmark

goos: linux
goarch: amd64
pkg: github.com/ausrasul/mem_cache
cpu: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
BenchmarkWrite-10                 807036              1676 ns/op
BenchmarkOverwrite-10            4153810               288.4 ns/op
BenchmarkRead-10                 5202807               242.5 ns/op
BenchmarkReadMiss-10             5180121               217.8 ns/op

BenchmarkWriteGoMap-10           1000000              1714 ns/op
BenchmarkOverwriteGoMap-10      16097797                75.41 ns/op
BenchmarkReadGoMap-10           49931186                21.96 ns/op
BenchmarkReadMissGoMap-10       82587925                14.12 ns/op
PASS
ok      github.com/ausrasul/mem_cache   11.335s
